using SentientArchitect.Domain.Abstractions;
using SentientArchitect.Domain.Enums;

namespace SentientArchitect.Domain.Entities;

public class Tag : BaseEntity
{
    public Tag(string name, TagCategory category, bool isAutoGenerated = false)
    {
        Name = name;
        Category = category;
        IsAutoGenerated = isAutoGenerated;
        KnowledgeItemTags = [];
    }

    private Tag()
    {
        KnowledgeItemTags = [];
    }

    public string Name { get; private set; } = string.Empty;
    public TagCategory Category { get; private set; }
    public bool IsAutoGenerated { get; private set; }

    public ICollection<KnowledgeItemTag> KnowledgeItemTags { get; private set; }
}
