using SentientArchitect.Domain.Enums;

namespace SentientArchitect.Domain.Entities;

/// <summary>
/// Categorization tag for KnowledgeItems.
/// Tags can be AI-generated (auto-tagging during ingestion) or user-created.
/// Related to KnowledgeItem via the KnowledgeItemTag join entity (M:N).
/// </summary>
public class Tag
{
    /// <summary>EF Core requires a parameterless constructor. Never call this directly.</summary>
    private Tag() { }

    public Guid Id { get; private set; }
    public string Name { get; private set; } = default!;
    public TagCategory Category { get; private set; }
    public bool IsAutoGenerated { get; private set; }

    /// <summary>
    /// Creates a new Tag. Name is unique within a category (enforced at DB level).
    /// </summary>
    public static Tag Create(string name, TagCategory category, bool isAutoGenerated = false)
    {
        if (string.IsNullOrWhiteSpace(name))
            throw new ArgumentException("Tag name cannot be empty.", nameof(name));

        return new Tag
        {
            Id = Guid.NewGuid(),
            Name = name.Trim().ToLowerInvariant(),
            Category = category,
            IsAutoGenerated = isAutoGenerated
        };
    }

    /// <summary>
    /// Renames the tag. Preserves lowercase normalization.
    /// </summary>
    public void Rename(string newName)
    {
        if (string.IsNullOrWhiteSpace(newName))
            throw new ArgumentException("Tag name cannot be empty.", nameof(newName));

        Name = newName.Trim().ToLowerInvariant();
    }
}
