using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SentientArchitect.Domain.Entities;

namespace SentientArchitect.Infrastructure.Persistence.Configurations;

/// <summary>
/// Fluent API configuration for Tag.
/// Unique index on (Name, Category) prevents duplicate tags within the same category.
/// </summary>
public class TagConfiguration : IEntityTypeConfiguration<Tag>
{
    public void Configure(EntityTypeBuilder<Tag> builder)
    {
        builder.ToTable("Tags");

        builder.HasKey(t => t.Id);

        builder.Property(t => t.Name)
            .IsRequired()
            .HasMaxLength(200);

        builder.Property(t => t.Category)
            .IsRequired()
            .HasConversion<string>()
            .HasMaxLength(50);

        builder.Property(t => t.IsAutoGenerated)
            .IsRequired();

        // Unique index: no duplicate tag names within the same category
        builder.HasIndex(t => new { t.Name, t.Category })
            .IsUnique();
    }
}
